### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by cg-cnu** [cg-cnu/mariSublime#3]
- Improve the instructions for downloading.
- Add instructions for changing the shortcuts.

**Comment by deenadrien** [comment]
Hello @cg-cnu , I'm beginner and I would like to contribute for my first time.

Are you asking to create some downloading instruction on your readme ?

**Comment by cg-cnu** [comment]
Hey @deenadrien Thanks for your interest to contribute to opensource. This is a old issue, I have created my myself and never bothered to finish. 

I you want to make some contribution, I would suggest you to look for issues over at  [DAV Foundation](http://github.com/davfoundation/). I can help find a beginner issue for you over there. Thanks!

**Comment by cg-cnu** [comment]
Hey @deenadrien Feel free to comment on this issue https://github.com/DAVFoundation/missioncontrol/issues/156 that you would like to work on it. I can assign it to you 😄
